guard: major clean up

diff --git a/guard b/guard
--- a/guard
+++ b/guard
@@ -10,12 +10,17 @@
 #version 0.12 06.02.08 -- remove base name
 #version 0.13 06.03.08 -- add --self
 #version 0.14 16.04.08 -- better version system
+#version 0.2  04.06.12 -- major clean up
 
 usage="Usage: ${0##*/} file1 <file2> ..."
 runcom="make"
 quiet="no"
-xpdf=""
-let waittime=3
+waittime=3
+
+die() {
+  echo -e "$*" >&2
+  exit 1
+}
 
 help () {
   cat << eof
@@ -28,7 +33,6 @@ OPTIONS:
                     Default: $waittime
 -s, --self          Add first file to command
 -q, --quiet         Be a little bit quiet
-    --xpdf          Start xpdf for "file1.pdf"
 -h, --help          Show this help
 -v, --version       Show version
 
@@ -53,11 +57,8 @@ while [ "${1#-}" != "$1" ]; do
     runcom=$2
     shift 2;;
    -t | --time)
-    let waittime=$2
-    if [ ! "$waittime" -gt 0 ]; then
-      echo Argument of -t should be int and bigger than 0
-      exit 1
-    fi
+    waittime=$2
+    [[ $waittime -gt 0 ]] || die "Argument of -t should be int and bigger than 0"
     shift 2;;
    -q | --quiet)
     quiet="yes"
@@ -65,87 +66,53 @@ while [ "${1#-}" != "$1" ]; do
    -s | --self)
     self="yes"
     shift ;;
-   --xpdf)
-    xpdf="yes"
-    shift ;;
    -h | --help)
     help
+    exit 0;;
+   --hg)
+    echo "${0##*/}: $(sed -ne 's/^#version.* -- \(.*$\)/\1/p' $0 | sed -n '$p')"
     exit 0;;
    -v | --version)
     echo "${0##*/}", $(sed -ne 's/^#\(version.*\) -- .*$/\1/p' $0 | sed -n '$p') by C. Junghans
     exit 0;;
   *)
-   echo Unknown option \'$1\' - ignored
+   die "Unknown option '$1'"
    shift ;;
  esac
 done
 
-if [ -z "$1" ]; then
-  echo No file given !
-  echo $usage
-  echo Help with -h
-  exit 1
-fi
+[[ -z $1 ]] && die "No file given !\n$usage\nHelp with -h"
 
-if [ "$runcom" = "make" ]; then
-  if [ ! -r "Makefile" ]; then
-    echo No Makefile found
-    echo Help with -h
-    exit 1;
-  fi
-fi
+[[ $self = yes ]] && runcom="$runcom $1"
 
-if [ "$self" = "yes" ]; then
-   runcom="$runcom $1"
-fi
-
-let i=0
-for myfile do
-  filename[$i]=$myfile
-  if [ ! -r $myfile ]; then
-    echo $myfile not found or readable
-    exit 1;
-  else
-    modtime[$i]=$(ls -l --time-style=+%s $myfile | awk '{print $6}' )
-  fi
-  shift
-  let i++
+i=0
+for f in "$@"; do
+  filename[$i]=$f
+  [[ -f $f ]] || die "$f not found or readable"
+  checksum[$i]=$(sha1sum $f)
+  (( i++ ))
 done
 
-echo Guarding files ${filename[*]}
-echo for doing \"$runcom\" every $waittime secs
+echo "Guarding files ${filename[*]}"
+echo "for doing '$runcom' every $waittime secs"
 
 $runcom
-
-if [ "$xpdf" = "yes" ]; then
-   pdfname="${filename[0]%tex}pdf"
-   echo Starting xpdf $pdfname
-   if [ -r "$pdfname" ]; then
-      xpdf ${filename[0]%tex}pdf &
-   else
-     echo Error PDF not found - try without --xpdf or check name!
-     exit
-   fi
-fi
 
 echo ${0##*/} is waiting...  
 while true; do
   sleep $waittime
   run="no"
-  if [ "$quiet" = "no" ]; then
-    echo ${0##*/} is waiting...  
-  fi
+  [[ "$quiet" = "no" ]] && echo "${0##*/} is waiting..."
   for (( i=0;i<${#filename[*]};i++)); do
-    let newmodtime=$(ls -l --time-style=+%s ${filename[$i]} | awk '{print $6}' )
-    if [ "$newmodtime" -ne "${modtime[$i]}" ]; then
-      echo \"${filename[$i]}\" was changed!
-      let modtime[$i]=$newmodtime
+    newchecksum=$(sha1sum ${filename[$i]})
+    if [[ $newchecksum != ${checksum[$i]} ]]; then
+      echo "'${filename[$i]}' has changed!"
+      checksum[$i]=$newchecksum
       run="yes"
     fi
   done
-  if [ "$run" = "yes" ]; then
+  if [[ $run = yes ]]; then
     $runcom
     echo ${0##*/} is waiting...
   fi
 done
-#fs md5sum e54ec7077bf4216fbddc3c0d901cff8c
